apiVersion: v1
kind: Service
metadata:
  name: call-my-owner-back-lb
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 9999
      protocol: TCP
  selector:
    app: call-my-owner-back
