apiVersion: apps/v1
kind: Deployment
metadata:
  name: call-my-owner-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: call-my-owner-front
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: call-my-owner-front
    spec:
      containers:
        - image: ruslana/call_my_owner_front
          imagePullPolicy: Always
          name: call-my-owner-front
          ports:
            - containerPort: 80
