apiVersion: v1
kind: Service
metadata:
  name: call-my-owner-front-lb
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: call-my-owner-front
