apiVersion: apps/v1
kind: Deployment
metadata:
  name: call-my-owner-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: call-my-owner-mongo
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: call-my-owner-mongo
    spec:
      containers:
        - image: bitnami/mongodb:latest
          imagePullPolicy: Always
          name: call-my-owner-mongo
          ports:
            - containerPort: 27017
