apiVersion: v1
kind: Service
metadata:
  name: call-my-owner-mongo
  labels:
    app: call-my-owner-mongo
spec:
  selector:
    app: call-my-owner-mongo
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
